// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: dapr/proto/internals/v1/scheduler.proto

package internals

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// InternalSchedulerCallbackClient is the client API for InternalSchedulerCallback service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InternalSchedulerCallbackClient interface {
	// Callback RPC for job schedule being at 'trigger' time
	TriggerJobCallback(ctx context.Context, in *TriggerJobRequest, opts ...grpc.CallOption) (*TriggerJobResponse, error)
}

type internalSchedulerCallbackClient struct {
	cc grpc.ClientConnInterface
}

func NewInternalSchedulerCallbackClient(cc grpc.ClientConnInterface) InternalSchedulerCallbackClient {
	return &internalSchedulerCallbackClient{cc}
}

func (c *internalSchedulerCallbackClient) TriggerJobCallback(ctx context.Context, in *TriggerJobRequest, opts ...grpc.CallOption) (*TriggerJobResponse, error) {
	out := new(TriggerJobResponse)
	err := c.cc.Invoke(ctx, "/dapr.proto.internals.v1.InternalSchedulerCallback/TriggerJobCallback", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InternalSchedulerCallbackServer is the server API for InternalSchedulerCallback service.
// All implementations should embed UnimplementedInternalSchedulerCallbackServer
// for forward compatibility
type InternalSchedulerCallbackServer interface {
	// Callback RPC for job schedule being at 'trigger' time
	TriggerJobCallback(context.Context, *TriggerJobRequest) (*TriggerJobResponse, error)
}

// UnimplementedInternalSchedulerCallbackServer should be embedded to have forward compatible implementations.
type UnimplementedInternalSchedulerCallbackServer struct {
}

func (UnimplementedInternalSchedulerCallbackServer) TriggerJobCallback(context.Context, *TriggerJobRequest) (*TriggerJobResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TriggerJobCallback not implemented")
}

// UnsafeInternalSchedulerCallbackServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InternalSchedulerCallbackServer will
// result in compilation errors.
type UnsafeInternalSchedulerCallbackServer interface {
	mustEmbedUnimplementedInternalSchedulerCallbackServer()
}

func RegisterInternalSchedulerCallbackServer(s grpc.ServiceRegistrar, srv InternalSchedulerCallbackServer) {
	s.RegisterService(&InternalSchedulerCallback_ServiceDesc, srv)
}

func _InternalSchedulerCallback_TriggerJobCallback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TriggerJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalSchedulerCallbackServer).TriggerJobCallback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dapr.proto.internals.v1.InternalSchedulerCallback/TriggerJobCallback",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalSchedulerCallbackServer).TriggerJobCallback(ctx, req.(*TriggerJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InternalSchedulerCallback_ServiceDesc is the grpc.ServiceDesc for InternalSchedulerCallback service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InternalSchedulerCallback_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dapr.proto.internals.v1.InternalSchedulerCallback",
	HandlerType: (*InternalSchedulerCallbackServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TriggerJobCallback",
			Handler:    _InternalSchedulerCallback_TriggerJobCallback_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dapr/proto/internals/v1/scheduler.proto",
}
